from datetime import datetime
from typing import TYPE_CHECKING, Any, Optional

from app.models.base import BaseModel
from sqlalchemy import JSON, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

if TYPE_CHECKING:
    from app.models.case import Case
    from app.models.cdr_record import CDRRecord
    from app.models.tracking_result import TrackingResult


class MovementEvent(BaseModel):
    """A single reconstructed movement event in a chronological path sequence.

    Movement events are generated by merging CDR records with Kalman-smoothed
    tracking data, then classifying handovers (cell tower transitions) and
    computing kinematic properties (speed, heading, distance, dwell time).
    """

    __tablename__ = "movement_events"

    case_id: Mapped[int] = mapped_column(
        ForeignKey("cases.id", ondelete="CASCADE"), nullable=False, index=True
    )
    cdr_record_id: Mapped[int | None] = mapped_column(
        ForeignKey("cdr_records.id", ondelete="SET NULL"), nullable=True
    )
    tracking_result_id: Mapped[int | None] = mapped_column(
        ForeignKey("tracking_results.id", ondelete="SET NULL"), nullable=True
    )

    sequence_number: Mapped[int] = mapped_column(Integer, nullable=False)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    timestamp: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True
    )

    latitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True)

    from_cgi: Mapped[str | None] = mapped_column(String(100), nullable=True)
    to_cgi: Mapped[str | None] = mapped_column(String(100), nullable=True)

    speed_kmh: Mapped[float | None] = mapped_column(Float, nullable=True)
    heading_deg: Mapped[float | None] = mapped_column(Float, nullable=True)
    distance_from_prev_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    dwell_time_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)

    metadata_json: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    case: Mapped["Case"] = relationship("Case", back_populates="movement_events")
    cdr_record: Mapped[Optional["CDRRecord"]] = relationship("CDRRecord")
    tracking_result: Mapped[Optional["TrackingResult"]] = relationship("TrackingResult")
