"""Add composite indexes for CDR and Movement

Revision ID: 17cf8523c284
Revises: 6de0cb9691b5
Create Date: 2026-08-01 11:58:42.755241

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "17cf8523c284"
down_revision: Union[str, Sequence[str], None] = "6de0cb9691b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_cdr_records_case_cgi", "cdr_records", ["case_id", "first_cgi"], unique=False
    )
    op.create_index(
        "ix_cdr_records_case_imei", "cdr_records", ["case_id", "imei"], unique=False
    )
    op.create_index(
        "ix_cdr_records_case_target",
        "cdr_records",
        ["case_id", "target_number"],
        unique=False,
    )
    op.create_index(
        "ix_cdr_records_case_timestamp",
        "cdr_records",
        ["case_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_movement_events_case_timestamp",
        "movement_events",
        ["case_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_movement_events_case_timestamp", table_name="movement_events")
    op.drop_index("ix_cdr_records_case_timestamp", table_name="cdr_records")
    op.drop_index("ix_cdr_records_case_target", table_name="cdr_records")
    op.drop_index("ix_cdr_records_case_imei", table_name="cdr_records")
    op.drop_index("ix_cdr_records_case_cgi", table_name="cdr_records")
    # ### end Alembic commands ###
