"""initial_migration

Revision ID: 1fae7e063a04
Revises: 
Create Date: 2026-07-26 12:22:26.909411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fae7e063a04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('towers',
    sa.Column('tower_name', sa.String(length=255), nullable=False),
    sa.Column('cgi', sa.String(length=100), nullable=True),
    sa.Column('mcc', sa.String(length=10), nullable=True),
    sa.Column('mnc', sa.String(length=10), nullable=True),
    sa.Column('lac', sa.String(length=50), nullable=True),
    sa.Column('ci', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_category', sa.String(length=50), nullable=False),
    sa.Column('resolution_method', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_towers_cgi'), 'towers', ['cgi'], unique=False)
    op.create_index(op.f('ix_towers_ci'), 'towers', ['ci'], unique=False)
    op.create_index(op.f('ix_towers_id'), 'towers', ['id'], unique=False)
    op.create_index(op.f('ix_towers_lac'), 'towers', ['lac'], unique=False)
    op.create_index(op.f('ix_towers_mcc'), 'towers', ['mcc'], unique=False)
    op.create_index(op.f('ix_towers_mnc'), 'towers', ['mnc'], unique=False)
    op.create_table('cases',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('parsed_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_id'), 'import_jobs', ['id'], unique=False)
    op.create_table('localization_results',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('estimated_latitude', sa.Float(), nullable=False),
    sa.Column('estimated_longitude', sa.Float(), nullable=False),
    sa.Column('error_m', sa.Float(), nullable=True),
    sa.Column('computation_time_ms', sa.Float(), nullable=True),
    sa.Column('signals_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localization_results_id'), 'localization_results', ['id'], unique=False)
    op.create_table('measurements',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('measurement_code', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rssi_dbm', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timing_advance', sa.Float(), nullable=True),
    sa.Column('uncertainty_m', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_code')
    )
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_table('cdr_records',
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('target_number', sa.String(length=50), nullable=True),
    sa.Column('b_party_number', sa.String(length=50), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('first_cgi', sa.String(length=100), nullable=True),
    sa.Column('first_bts_location', sa.Text(), nullable=True),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('last_cgi', sa.String(length=100), nullable=True),
    sa.Column('last_bts_location', sa.Text(), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('imsi', sa.String(length=50), nullable=True),
    sa.Column('smsc_number', sa.String(length=50), nullable=True),
    sa.Column('roaming_network', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdr_records_b_party_number'), 'cdr_records', ['b_party_number'], unique=False)
    op.create_index(op.f('ix_cdr_records_case_id'), 'cdr_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_cdr_records_first_cgi'), 'cdr_records', ['first_cgi'], unique=False)
    op.create_index(op.f('ix_cdr_records_id'), 'cdr_records', ['id'], unique=False)
    op.create_index(op.f('ix_cdr_records_imei'), 'cdr_records', ['imei'], unique=False)
    op.create_index(op.f('ix_cdr_records_import_job_id'), 'cdr_records', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_cdr_records_imsi'), 'cdr_records', ['imsi'], unique=False)
    op.create_index(op.f('ix_cdr_records_last_cgi'), 'cdr_records', ['last_cgi'], unique=False)
    op.create_index(op.f('ix_cdr_records_operator'), 'cdr_records', ['operator'], unique=False)
    op.create_index(op.f('ix_cdr_records_target_number'), 'cdr_records', ['target_number'], unique=False)
    op.create_index(op.f('ix_cdr_records_timestamp'), 'cdr_records', ['timestamp'], unique=False)
    op.create_table('confidence_results',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('localization_result_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('error_ellipse_semi_major_m', sa.Float(), nullable=True),
    sa.Column('error_ellipse_semi_minor_m', sa.Float(), nullable=True),
    sa.Column('error_ellipse_orientation_deg', sa.Float(), nullable=True),
    sa.Column('gdop', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['localization_result_id'], ['localization_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_results_id'), 'confidence_results', ['id'], unique=False)
    op.create_table('tracking_results',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('localization_result_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('smoothed_latitude', sa.Float(), nullable=False),
    sa.Column('smoothed_longitude', sa.Float(), nullable=False),
    sa.Column('velocity_lat', sa.Float(), nullable=False),
    sa.Column('velocity_lon', sa.Float(), nullable=False),
    sa.Column('velocity_mps', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('error_m', sa.Float(), nullable=True),
    sa.Column('computation_time_ms', sa.Float(), nullable=True),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['localization_result_id'], ['localization_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_results_id'), 'tracking_results', ['id'], unique=False)
    op.create_table('movement_events',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('cdr_record_id', sa.Integer(), nullable=True),
    sa.Column('tracking_result_id', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('from_cgi', sa.String(length=100), nullable=True),
    sa.Column('to_cgi', sa.String(length=100), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('distance_from_prev_m', sa.Float(), nullable=True),
    sa.Column('dwell_time_seconds', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cdr_record_id'], ['cdr_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracking_result_id'], ['tracking_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_events_case_id'), 'movement_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_movement_events_id'), 'movement_events', ['id'], unique=False)
    op.create_index(op.f('ix_movement_events_timestamp'), 'movement_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movement_events_timestamp'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_id'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_case_id'), table_name='movement_events')
    op.drop_table('movement_events')
    op.drop_index(op.f('ix_tracking_results_id'), table_name='tracking_results')
    op.drop_table('tracking_results')
    op.drop_index(op.f('ix_confidence_results_id'), table_name='confidence_results')
    op.drop_table('confidence_results')
    op.drop_index(op.f('ix_cdr_records_timestamp'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_target_number'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_operator'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_last_cgi'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_imsi'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_import_job_id'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_imei'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_id'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_first_cgi'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_case_id'), table_name='cdr_records')
    op.drop_index(op.f('ix_cdr_records_b_party_number'), table_name='cdr_records')
    op.drop_table('cdr_records')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_localization_results_id'), table_name='localization_results')
    op.drop_table('localization_results')
    op.drop_index(op.f('ix_import_jobs_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_towers_mnc'), table_name='towers')
    op.drop_index(op.f('ix_towers_mcc'), table_name='towers')
    op.drop_index(op.f('ix_towers_lac'), table_name='towers')
    op.drop_index(op.f('ix_towers_id'), table_name='towers')
    op.drop_index(op.f('ix_towers_ci'), table_name='towers')
    op.drop_index(op.f('ix_towers_cgi'), table_name='towers')
    op.drop_table('towers')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
