"""add_scenario_id_to_case

Revision ID: 95bd12db5c9f
Revises: 7a6f06c2fa7f
Create Date: 2026-07-08 16:08:26.995224

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95bd12db5c9f"
down_revision: str | Sequence[str] | None = "7a6f06c2fa7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scenario_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_cases_scenarios",
            "scenarios",
            ["scenario_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_constraint("fk_cases_scenarios", type_="foreignkey")
        batch_op.drop_column("scenario_id")
    # ### end Alembic commands ###
