"""Add tower_id to measurements

Revision ID: 9e7beaae84db
Revises: e6e4f2282afa
Create Date: 2026-08-06 11:25:43.866008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7beaae84db'
down_revision: Union[str, Sequence[str], None] = 'e6e4f2282afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('tower_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'tower_id')
    # ### end Alembic commands ###
