"""make_rssi_nullable

Revision ID: e6e4f2282afa
Revises: 17cf8523c284
Create Date: 2026-08-05 18:09:49.746214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e4f2282afa'
down_revision: Union[str, Sequence[str], None] = '17cf8523c284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.alter_column('rssi_dbm',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.alter_column('rssi_dbm',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
